version: '3.5'

services:
  postgres:
    container_name: postgres_deb
    image: debezium/postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - kafka-broker_kafka_network
networks:
  kafka-broker_kafka_network:
    external: true
