spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      connection-properties: stringtype=unspecified
    hikari:
      data-source-properties: stringtype=unspecified
      connection-timeout: 20000
      leakDetectionThreshold: 60000
      maximumPoolSize: ${DB_POOL_SIZE:2}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:person_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}